- web/app/themes/xrnl/assets/sass/app.scss
- web/app/themes/xrnl/header.php
Static top menu visible on desktop only (>800 px device width)
> Desktop nav

- web/app/themes/xrnl/assets/sass/_variables.scss
- web/app/themes/xrnl/assets/sass/form.scss
- web/app/themes/xrnl/assets/sass/press.scss
- web/app/themes/xrnl/assets/sass/typography.scss
- web/app/themes/xrnl/footer.php
- web/app/themes/xrnl/front-page.php
- Adds analytics from [simpleanalytics.com](https://simpleanalytics.com/)
- Styling and UI improvements
> analytics and small ui improvements

- .env.example
- .gitignore
- Dockerfile
- README.md
- config/environments/development.php
- docker-compose.yml
- vhost.conf
As simple as doing
```
docker-compose up -d
```
> Adds docker setup

- web/app/themes/xrnl/acf-json/en/group_5d5d1b4122894.json
- web/app/themes/xrnl/acf-json/nl/group_5d593b7d50cda.json
- web/app/themes/xrnl/rwb.php
Contains:
- Styling changes
- Custom field changes
- And a "Do more" section
> Update RWB page

- README.md
- composer.json
- composer.lock
- updates wordpress to `5.2.2`
- updates other plugins to latest versions
> update wordpress to 5.2.2

- web/app/themes/xrnl/acf-json/en/group_5d642864730fa.json
- web/app/themes/xrnl/acf-json/nl/group_5d6422d1b1e1b.json
- web/app/themes/xrnl/assets/sass/custom.scss
- web/app/themes/xrnl/assets/sass/form.scss
- web/app/themes/xrnl/assets/sass/rwb.scss
- web/app/themes/xrnl/front-page.php
- adds ability to customize home page hero section
- harmonizes styling issues with action network forms
> home page hero section and styling 

- web/app/themes/xrnl/functions.php
Fix for https://github.com/DaanMeijer/extinction-rebellion-nl/issues/25
> Changed meetup_events slug to events

- web/app/themes/xrnl/acf-json/group_5d8cbc3a273d8.json
- web/app/themes/xrnl/assets/sass/app.scss
- web/app/themes/xrnl/assets/sass/join.scss
- web/app/themes/xrnl/functions.php
- web/app/themes/xrnl/join.php
> adds join page

- web/app/themes/xrnl/about.php
- web/app/themes/xrnl/acf-json/group_5d8cc00dbe5b7.json
- web/app/themes/xrnl/assets/sass/about.scss
- web/app/themes/xrnl/assets/sass/app.scss
> adds about page

- web/app/themes/xrnl/archive-meetup_events.php
- web/app/themes/xrnl/functions.php
See this card: https://trello.com/c/94d31ca8/62-improve-local-group-events-filter
> Only display event locations with events

- web/app/themes/xrnl/acf-json/group_5e903166ebd61.json
- web/app/themes/xrnl/assets/sass/app.scss
- web/app/themes/xrnl/assets/sass/community.scss
- web/app/themes/xrnl/community_group-archive.php
- web/app/themes/xrnl/functions.php
- web/app/themes/xrnl/single-community_group.php
This adds
- a template for single community group pages
- a template for an overview of community groups
- a new "Community group" post type in functions.php
- custom fields
- some CSS
> Community group pages

- web/app/themes/xrnl/assets/sass/join.scss
- web/app/themes/xrnl/doe-mee.php
This adds CSS for giving the new join page sections padding and text-alignment properties.
> Update Join page CSS

- web/app/themes/xrnl/footer.php
- web/app/themes/xrnl/header.php
This adds the [tracking code](https://developer.matomo.org/guides/tracking-javascript-guide) for Matomo in the `<head>` section in `header.php`, and removes the reference and script for Simpleanalytics in `footer.php`.
> Switch to matomo

- web/app/themes/xrnl/acf-json/group_5d9678d92c76e.json
- web/app/themes/xrnl/front-page.php
[ Since there are more SEO improvements on our to-do list, maybe we can keep adding to this PR as we go along ]
1. Display alt text for image on home page
- `group_5d9678d92c76e.json`: Return an array with metadata for the image, not just the URL
- `front-page.php`: Insert alt text into `<img>` tag
> SEO improvements

- web/app/themes/xrnl/acf-json/group_5f54069104562.json
- web/app/themes/xrnl/acf-json/group_5f5f923355ed4.json
- web/app/themes/xrnl/assets/sass/app.scss
- web/app/themes/xrnl/assets/sass/petition.scss
- web/app/themes/xrnl/functions.php
- web/app/themes/xrnl/petition.php
> Petitions template and custom fields

- web/app/themes/xrnl/acf-json/group_5f54069104562.json
- web/app/themes/xrnl/petition.php
Fixed all the bugs mentioned in [this Trello card](https://trello.com/c/xa6jEoAk).
> Petition page improvements

- web/app/themes/xrnl/acf-json/group_5f5f434632c10.json
- web/app/themes/xrnl/assets/images/emn-dash.svg
- web/app/themes/xrnl/assets/sass/_variables.scss
- web/app/themes/xrnl/assets/sass/app.scss
- web/app/themes/xrnl/assets/sass/why-rebel.scss
- web/app/themes/xrnl/why-rebel.php
Implements the Why Rebel page.
> Add Why Rebel page

- web/app/themes/xrnl/acf-json/group_5f54069104562.json
- web/app/themes/xrnl/assets/sass/form.scss
- web/app/themes/xrnl/assets/sass/petition.scss
- web/app/themes/xrnl/petition.php
In this pull request I implement the changes mentioned in [this comment](https://github.com/xrnl/extinction-rebellion-nl/pull/81#pullrequestreview-487293330) of PR #81 
For the donation and sharing step, I have incorporated the HTML from #92. I incorporated it into a new branch instead of adding to the existing branch to avoid dreadful merge conflicts with the custom fields. Closes #92 
I also implemented some of the last bugs that were brought up about the petition page.
> Petition page funnel

- web/app/themes/xrnl/acf-json/group_5fc4ba51be42e.json
- web/app/themes/xrnl/archive-meetup_events.php
Implements the design below, using a new set of custom fields on the Events page.
(also, vertically centers the submit button of the event filters)
> Add featured event on the Events page

- web/app/themes/xrnl/acf-json/group_5fc7bc995cc35.json
- web/app/themes/xrnl/intro-talk.php
heya, this is the page template for the intro talk and some custom fields.
Please excuse my javascript
Any comments welcome :)
> Intro talk page

- web/app/themes/xrnl/intro-talk.php
Classic copy-paste mistake 🙈 
Now the correct custom field is rendered below the screenshot.
> Bug fix for the intro talk page

- web/app/themes/xrnl/single-xrnl_local_group.php
This just updates the "View all groups" link to point to the new page at `/lokale-groepen`.
> Update single local group template

- composer.json
- composer.lock
I am new to XR and XR Tech/Website. My first task is to get the XR website running locally on my Macbook. I followed the instructions in the README. 
When running `docker-compose up` I noticed some error messages in the PHP-installation and the WP website did not run. It showed 3 problems. I only show the first problem below:
```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Root composer.json requires wpackagist-plugin/wordpress-seo ^11.0, it is satisfiable by wpackagist-plugin/wordpress-seo[11.9] from lock repo but wpackagist-plugin/wordpress-seo[dev-trunk, 12.0, ..., 12.9.1, 13.0, ..., 13.5, 14.0, ..., 14.9, 15.0, ..., 15.6.2] from composer repo (https://wpackagist.org) …
```
> Wordpress-seo plugin causes a package dependency error during docker installation

- CONTRIBUTING.md
- README.md
- SUPPORT.md
- docs/becoming_admin.md
- docs/sync-production-data.md
This pull request closes these two long-standing tasks that will make the onboarding of new people much easier:
- documentation improvements: https://trello.com/c/ZlUWNbso
- contributing guides: https://trello.com/c/7Q4208nM
This merge request is aaalmost ready. I just need to add some final info in the contributing guidelines. I've already made this request so you can start reviewing the other text & so I can close this task before our meeting :innocent:
> Documentation improvements

- web/app/themes/xrnl/acf-json/group_5d9678d92c76e.json
- web/app/themes/xrnl/front-page.php
Two small changes to improve embedding from XR Tube:
- change the aspect ratio to 16:9
- let the home page custom field for video accept an embed code
> Embed front page video from XR Tube

- web/app/themes/xrnl/acf-json/group_5d9678d92c76e.json
Just a quick bugfix for the home page; somehow the return format of some image custom fields got messed up in #139.
> Homepage image custom fields return arrays

- web/app/themes/xrnl/about.php
- web/app/themes/xrnl/acf-json/group_6060f0baa2615.json
- web/app/themes/xrnl/citizen_assembly_faq.php
- web/app/themes/xrnl/citizen_assembly_home.php
- web/app/themes/xrnl/doe-mee.php
- web/app/themes/xrnl/functions.php
- web/app/themes/xrnl/structure_circles.php
Added custom field structure. Structure is a list of circle titles, descriptions and a link to the wiki. Also created structure_circles.php. I added a screenshot of how the /structuur page looks in development.
When deployed in production, the /structuur page needs to point to the template structure_circles. Then the content for the organisational structure can be added.
And then the second part of the Trello task can be completed: making references to the organisational structure elements.
Please review this pull request.
> working circles information

- web/app/themes/xrnl/about.php
- web/app/themes/xrnl/archive-meetup_events.php
- web/app/themes/xrnl/citizen_assembly_home.php
- web/app/themes/xrnl/class-wp-bootstrap-navwalker.php
- web/app/themes/xrnl/doe-mee.php
- web/app/themes/xrnl/footer.php
- web/app/themes/xrnl/front-page.php
- web/app/themes/xrnl/functions.php
- web/app/themes/xrnl/header.php
- web/app/themes/xrnl/intro-talk.php
- web/app/themes/xrnl/local_group-archive.php
- web/app/themes/xrnl/volunteer_vacancy-archive.php
- web/app/themes/xrnl/why-rebel.php
This PR contains the code part of this task: https://trello.com/c/ymvxQrip
The analytics code is implemented in accordance with the specification: https://wiki.extinctionrebellion.nl/Main/Tracking
In the function I've created, I'm escaping the URL because of what's mentioned in [this SOF post](https://stackoverflow.com/questions/6768793/get-the-full-url-in-php): 
> using this code has security implications. The client can set HTTP_HOST and REQUEST_URI to any arbitrary value it wants.
To-do list:
input.
> Button analytics

- web/app/themes/xrnl/acf-json/group_5ebfec514504e.json
- web/app/themes/xrnl/assets/sass/roles.scss
- web/app/themes/xrnl/functions.php
- web/app/themes/xrnl/single-volunteer_vacancy.php
- web/app/themes/xrnl/volunteer_vacancy-archive.php
For [this Trello task](https://trello.com/c/0Zxh1ZsB/271-volunteer-page-improvements)
It's meant more as a concept than the final thing, especially the text. 
- Removed local group roles
- Working group filter now works with javascript
- Adjusted layout
- Removed published date
- Changed strings above contact details
> Updates for volunteer page and single volunteer role

- web/app/themes/xrnl/assets/sass/local.scss
- web/app/themes/xrnl/local_group-archive.php
Added custom logo of local group to the list of local groups (local_group-archive.php). Added a css class to make the logo nicely round. See also: https://trello.com/c/u5dBN8sI
> Added logo of local group to the list of local groups

- web/app/themes/xrnl/acf-json/group_61103043230d7.json
- web/app/themes/xrnl/assets/sass/app.scss
- web/app/themes/xrnl/assets/sass/rebellion.scss
- web/app/themes/xrnl/doe-mee.php
- web/app/themes/xrnl/functions.php
- web/app/themes/xrnl/rebellion.php
In this PR I'm adding two new sections to the rebellion page:
1. section with a form where people can sign up:
2. section with foldout menus where people can find all the info about the rebellion
> Rebellion page features

- web/app/themes/xrnl/petition.php
- web/app/themes/xrnl/single-xrnl_local_group.php
- web/app/themes/xrnl/why-rebel.php
@SamLubbers Merging this quickly in order to solve [this issue](https://github.com/xrnl/extinction-rebellion-nl/pull/153/files#r695474708) in #153 😇
> Remove getSection function from page templates

- composer.json
- composer.lock
Only a minor version bump but it has some more [security updates](https://wordpress.org/support/wordpress-version/version-5-8-1/).
> Update Wordpress to 5.8.1

- web/app/themes/xrnl/footer.php
Removed donate button from the footer as per [Trello card](https://trello.com/c/wag0q06m/318-remove-all-mentions-from-donations-except-in-navigation-bar).
> Remove donate button from footer partial

- CONTRIBUTING.md
@franei very small but necessary change :v: I left it to every other thursday because we'll probably revert to that after the rebellion
> updated time of the website meeting

- web/app/themes/xrnl/acf-json/group_617fafaa38e32.json
- web/app/themes/xrnl/assets/js/smooth-scrolling.js
- web/app/themes/xrnl/assets/sass/app.scss
- web/app/themes/xrnl/assets/sass/landbouw-campaign.scss
- web/app/themes/xrnl/footer.php
- web/app/themes/xrnl/functions.php
- web/app/themes/xrnl/header.php
- web/app/themes/xrnl/landbouw-campaign.php
This is the page for the XR Landbouw campaign. All the methods for interacting with AN are just lifted off the `petition.php` that we already have. The page layout both before and after form submission is quite different though.
Here is a quick summary of the changes/additions:
- `header.php` - accept an optional argument for hiding the navbar
- `footer.php` - accept an optional argument for hiding the footer
- `assets/js/smooth-scrolling.js` - add js-powered smooth scrolling
- `functions.php` - register the smooth-scrolling js
- `landbouw-campaign.php` - page template
- `assets/sass/landbouw-campaign.scss` - CSS for the page template
- `assets/sass/app.scss` - use the new CSS
- `acf-json/group_617fafaa38e32.json` - custom fields
I'm going to merge this now because the campaign starts in …
> XR Landbouw petition

- .gitignore
- composer.json
- composer.lock
- web/app/themes/xrnl/assets/sass/_variables.scss
- web/app/themes/xrnl/assets/sass/app.scss
- web/app/themes/xrnl/assets/sass/shop-banner.scss
- web/app/themes/xrnl/assets/sass/shop.scss
- web/app/themes/xrnl/assets/sass/starburst.scss
- web/app/themes/xrnl/functions.php
- web/app/themes/xrnl/header.php
- web/app/themes/xrnl/shop.php
- web/app/themes/xrnl/single-product.php
- web/app/themes/xrnl/template-parts/shop-banner.php
This Pull Request contains all the styling and plugins needed for setting up the webshop for the XR hete klimaat kalender. I added a new shortcode (`shop-banner`) for  the banner on the shop page.
This is a list of changes:
- Added `shop-banner.php` for the new shop-banner shortcode.
- Registered the shop-banner shortcode in `functions.php`
- Added styling in these files: `shop-banner.scss` / `shop.scss` / `starburst.scss`
- Added the `wpml/wpml-woo-commerce-multilingual` to the composer.json `repositories` property and `require` list.
- Added the WooCommerce plugin via the composer install command. Source: `wpackagist-plugin/woocommerce`
**Shop page**
**Product page**
**Shop cart**
> XR Hete klimaatkalender - webshop Woo Commerce
