composer.json
composer.lock
web/app/themes/xrnl/archive-meetup_events.php
web/app/themes/xrnl/assets/sass/_variables.scss
web/app/themes/xrnl/assets/sass/app.scss
web/app/themes/xrnl/assets/sass/custom.scss
web/app/themes/xrnl/assets/sass/events.scss
web/app/themes/xrnl/front-page.php
web/app/themes/xrnl/functions.php
web/app/themes/xrnl/header.php

Closes #8 
This PR adds import-meetup-events plugin which gets all events from meetup. 
Todo after merge:
**Screenshots:**

adds events listing

---

docker-compose.yml

This is necessary to read database files from the host machine on Windows. 
For more information see:
https://github.com/docker-library/mariadb/issues/95#issuecomment-407839431
This seems to fix the issues with running the site locally on Windows.

Change mariadb docker command

---

web/app/themes/xrnl/footer.php

This removes the headings above the two navigation lists in the page footer. The links are to be restructured into two lists with five items each, and the headings will no longer be appropriate.
Current footer: 
New footer with the re-ordered navigation lists (which still needs to be done in WP admin once this is live):

Removing navigation list headings in footer

---

web/app/themes/xrnl/header.php

This is a minor change to the appearance of the mobile (vertical) navigation menu.
The social & donate buttons appear somewhat misaligned with the rest of the mobile nav menu. This is because the `<ul>` with the buttons is nested inside the `<div>` of the language switcher. By taking the list out of the div, it becomes its own flex-item and flows underneath the switcher in vertical view. The desktop-width horizontal navbar stays unchanged.
Closes #44.

Aligning the social buttons in the mobile navigation menu

---

web/app/themes/xrnl/assets/sass/join.scss
web/app/themes/xrnl/join.php

The form to leave the email behind has been moved much higher on the join page.
Before it was all the way at the bottom. Now it is appears before events and local groups. Note that in this screenshot the action network form is not rendered because the plugin isn't working locally for me at the moment. 
Getting people's contact details is a crucial aspect for integrating them into the movement. Once we have their email, we can invite them to events in their area, inform them of upcoming actions etc. By having the form higher up on the page we hope to get more people signing up.
This decision is supported by Moritz from the integration circle and Koen from the design circle. They support this decision because:
1. There are no local events at the moment.
2. Events are already widely …

Join page restructuring

---

web/app/themes/xrnl/resources.php

In the current version of the resources page, the `src` of the iframe uses `http`. The mix of https in the parent page and http in the iframe is getting blocked by browsers for security reasons (even though http requests are forwarded to https automatically).
Now that the resources library is on a new host with SSL certificate, we can just change the `src` to `https` and all should be fine.

Change iframe src to https

---

web/app/themes/xrnl/resources.php

The resource library now has a search function. In cases where there are many search results, the results list can extend beyond the page height, which requires the iframe height to expand accordingly.
That doesn't happen currently, so long results lists are getting cut off. We need a different method for calculating the height of the iframe. Fortunately it's already built into the [resizer utility](https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/parent_page/options.md), so we just need to change an option.

Adjust iframe height calculation method

---

web/app/themes/xrnl/about.php

The Principles and Values section should be linkable directly from outside. This can be done by linking to the page element's id, but it was not working because the P&V section was hidden by default.
This update just unhides the sections in the `topic` array by default. 
It also adds more informative page element IDs (was "topic-1", "topic-2" etc), so that we can link to
```
/en/wie-wij-zijn/#our-movement
/wie-wij-zijn/#onze-beweging
/en/wie-wij-zijn/#our-principles-and-values
/wie-wij-zijn/#uitgangspunten-kernwaarden
/en/wie-wij-zijn/#our-structure
/wie-wij-zijn/#onze-structuur
```
directly.

Make principles and values linkable

---

web/app/themes/xrnl/archive-meetup_events.php
web/app/themes/xrnl/footer.php

The Donate button in the page footer currently always points to the NL version of the donation page.
This adjusts the `href` according to the current locale.
Some strings on the Events page are not translatable currently.
This inserts `_e()` and `translate()` functions so that it can be fixed in the WP admin.

Fix translation issues 

---

web/app/themes/xrnl/acf-json/group_5ecc1fbe2efa9.json
web/app/themes/xrnl/doe-mee.php

This PR implements a [new layout](https://organise.earth/xr-netherlands/pl/gjhwy6h84pbcidkkfwb7qejjto) for the Join page with a new template and custom field set. 
The main change from the previous version is that every section can be hidden from the admin panel with a switch:
There are some new flexible elements in the groups, actions, and do-more sections.
This template has a new name because I'm thinking that this will make it easier to update the page without breaking it. This way we can take our time with setting up the new version and when it's ready we just change the permalink. Please tell me if this is bad idea :)

New join page template and CFs

---

web/app/themes/xrnl/doe-mee.php
web/app/themes/xrnl/header.php
web/app/themes/xrnl/single-community_group.php
web/app/themes/xrnl/single-volunteer_vacancy.php
web/app/themes/xrnl/volunteer_vacancy-archive.php

The `icl_object_id` function from the WPML plugin has been deprecated. This replaces it with the [new method](https://wpml.org/wpml-hook/wpml_object_id/) in the five page templates that use it. The new method already works in the version of WPML that we're currently running on the live site, so it shouldn't cause any issues (I've also tested it on a local instance).
By the way I'm not trying to be annoying with removing the tab characters; apparently my text editor does that automatically. Hope this is ok :)

Updates for new WPML version

---

web/app/themes/xrnl/archive-meetup_events.php

There are two small changes in this PR:
1. There was a reference to a variable called `$css_class` which doesn't seem to be defined anywhere & this breaks the page in recent versions of PHP. It now defaults to an empty string if the variable isn't set.
2. Remove a stray character

Fix PHP bug on Events archive page

---

web/app/themes/xrnl/assets/sass/_variables.scss

After updating the Advanced Custom Fields plugin, all links were suddenly underlined (?!?).
This changes the default text-decoration back to `none`.

CSS link-decoration quick-fix

---

web/app/themes/xrnl/archive-meetup_events.php
web/app/themes/xrnl/functions.php

This PR fixes two bugs in the events city filter:
The filter currently does not work 's Hertogenbosch as wp inserts a backslash in front of the apostrophe - stripping the backslashes from the city parameter fixes this.
Also, the logic used in "event_cities" is right now inconsistent with the actual event filter - this can cause the number of events appearing the cities dropdown to differ from the number of events displayed - this is also fixed.
I also removed the "cancelled / afgelast" filters as there are not a lot of cancelled events anymore and that filter is not very specific and could filter out events that are not actually cancelled

Fix events filter

---

web/app/themes/xrnl/archive-meetup_events.php
web/app/themes/xrnl/footer.php
web/app/themes/xrnl/resources.php

This implements one small change in the footer:
- Update the link to XR UK, as they've recently moved to a new domain.
...and two small changes on Events page:
- Remove the sentence below the search results that referred visitors to Facebook or Meetup.
- Don't refer people to FB and Meetup when there are no search results; instead show a "Clear filters" button which will reload the page without filters.
And two small changes for the resources template:
- Wrap the library iframe in a `div` for better scrolling behaviour on iOS.
- Send a message to the resource library telling it that it's being loaded inside an iframe.
When the library gets the message it will hide its (yet to be deployed) navigation bar. 
Like this, we can show a navigation bar when visitors arrive at …

Template updates

---

web/app/themes/xrnl/community_group-archive.php

This puts the text content of the community archive page into a paragraph above the cards.
See Trello card for the request [here](https://trello.com/c/j9FxpPHq/87-page-community-content).

Text content on community page

---

web/app/themes/xrnl/rwb.php

Addressing this [this request](https://trello.com/c/4yjGyqhQ/172-ux-smooth-scrolling) to enable smooth scrolling on the RWB page when the 'Sign up' button is clicked.

Enable smooth scrolling

---

web/app/themes/xrnl/assets/sass/app.scss
web/app/themes/xrnl/assets/sass/whydonate.scss

This defines the `whydonate` class for overwriting some of the default styling of the WhyDonate donation button, progress bar, and donation form. See [this Trello card](https://trello.com/c/LouTL1SI/70-add-whydonatenl-plugin-to-website) for the request and some before/after screenshots.
The `wd-center` class can be used for centering the button/progress bar:
```html
<div class="whydonate wd-center">
[whydonate id="weuzk"]
</div>
```

Overwrite CSS for the WhyDonate plugin

---

web/app/themes/xrnl/assets/sass/why-rebel.scss
web/app/themes/xrnl/why-rebel.php

This sets the maximum width for content on the Why Rebel page to 900px [as requested](https://trello.com/c/WFu2TMXq/202-page-why-rebel-max-900px).
Also adds an option to remove the bottom border on quote blocks, [see this card](https://trello.com/c/hZUuTXO9/204-page-about-us-add-quote).

Adjust layout on why-rebel page

---

web/app/themes/xrnl/functions.php

The `local_group` [custom post type](https://github.com/xrnl/extinction-rebellion-nl/pull/75) is causing a naming conflict with the "Local group" roles filter on the volunteer page.
In order to avoid this conflict we can just change the key under which the post type is registered with WP.
Thanks @Mananasi for figuring out the cause of the problem!

Avoid naming collision for local group custom post type

---

web/app/themes/xrnl/acf-json/group_5f1ad30f2103e.json
web/app/themes/xrnl/functions.php
web/app/themes/xrnl/single-xrnl_local_group.php

Minor improvements for two custom post types:
1. Volunteer vacancy:
- Disable the visual editor to prevent WP from inserting `&amp;` character. Closes #100 
2. Local group:
- Add ability to associate an author with a group
- Add ability to select images from the media library (instead  of pasting in the URL)

Improve custom post types

---

web/app/themes/xrnl/assets/sass/header.scss

From [Force Dutch mobile menu to 1 line](https://trello.com/c/z9BE0NFP/228-force-dutch-mobile-menu-to-1-line)
I did have issues reproducing this issue. I tried my best with the Google Chrome mobile emulator feature in the developer tools. I made the xxs version of the header image take up maximum of about a third of the screen. This allows the donate and join buttons to move in further.

Fixed buttons in header getting pushed to new line on some mobile devices

---

web/app/themes/xrnl/assets/sass/events.scss

This limits the event info to 2 lines and hides any overflowing text.
Closes #79. (well, partially ;) I think we can't actually prevent text on the images getting cut off, unless we want to start making sure that all images conform to a certain format)

Hide overflowing text in event info

---

web/app/themes/xrnl/acf-json/group_5fa311a77eb3b.json
web/app/themes/xrnl/acf-json/nl/group_5f5f923355ed4.json
web/app/themes/xrnl/functions.php
web/app/themes/xrnl/template-parts/demands-list.php
web/app/themes/xrnl/why-rebel.php

Hey @SamLubbers & @jessejk89 this is meant as a sort of proposal. If you have time, I would really appreciate your thoughts :)
Because we've recently created an options page and are planning to add more items to it, I thought it would be useful to give it some structure. I also noticed that the API key for action network is currently visible (and editable) to all users, including authors, which is maybe not quite ideal because we're about to add many more users for the local groups.
So I thought it would be worth making subpages, which thankfully is really easy.
Here I've made a settings page "XRNL Settings" with two subpages:
- Admin: only visible to admins, can be used for things like that API key
- Editorial: accessible for editors, can be used for editorial content like the CTA from …

Add ACF options sub pages

---

web/app/themes/xrnl/doe-mee.php

Addresses [this request](https://trello.com/c/ZUAHNciJ/246-html-id-toevoegen-aan-doe-mee-pagina-om-zo-te-kunnen-linken-naar-nieuwsbrief-inschrijven) to add an element ID to the sign-up section on the Join page, so that the section can be linked to directly.
The ID is translatable, so that people can use either one of these:
https://extinctionrebellion.nl/en/join#sign-up
https://extinctionrebellion.nl/doe-mee#schrijf-je-in

Add ID to signup section on Join page

---

web/app/themes/xrnl/about.php
web/app/themes/xrnl/acf-json/group_5f5f923355ed4.json
web/app/themes/xrnl/petition.php

This is only a quick follow-up to #102.
The ACF options page is now on the live site, and the demands are filled in.
This just changes the `petition` and `about` templates to use the new template-part for the demands, and tells the custom field for the AN key to show up on the ACF "admin" subpage.

Use ACF options

---

web/app/themes/xrnl/acf-json/group_5fb6956308903.json
web/app/themes/xrnl/assets/sass/local.scss
web/app/themes/xrnl/local_group-archive.php

What's in this PR:
- A template for an index page that lists all local groups, with links to their individual pages
- Custom fields for a few settings and text snippets
- CSS
Happy to implement any feedback :)

Local groups index page

---

web/app/themes/xrnl/functions.php

This changes the slug for the local groups custom post type.
After this, the permalinks for LGs will be like
```
extinctionrebellion.nl/groep/maastricht
extinctionrebellion.nl/en/groep/maastricht
```
When we deploy this we need to remember to flush the permalinks, which can be done by going to Settings > permalinks & then clicking on "save changes" (without making any changes)
We can independently decide where to put the overview page. It could be
```
extinctionrebellion.nl/lokale-groepen 
extinctionrebellion.nl/en/local-groups
```
If we change the URL for the overview page, we should remember to add a redirect from `/local` and `/en/local` to the new overview pages.

Change the slug for local groups

---

web/app/themes/xrnl/acf-json/group_5fc7bc995cc35.json
web/app/themes/xrnl/intro-talk.php

The screenshot on the intro talk page is no longer needed. 
This removes it from the template and from the custom fields.
The center section then looks like this:

Remove the center picture on the intro talk page

---

web/app/themes/xrnl/assets/js/xrnl-local-group-tabs.js
web/app/themes/xrnl/single-xrnl_local_group.php

The way in which `js` and `css` assets are loaded on local group pages is not ideal at the moment. This is causing some conflicts, and a bug that currently prevents the photo gallery from being displayed.
This fixes it by loading assets the wordpress way, using the `wp_enqueue_script` and `wp_enqueue_style` functions.
Also, the javascript for controlling the behaviour of the navigation tabs and the image gallery is now in a separate file and no longer inline with the page template.

Improve asset loading on local group pages

---

web/app/themes/xrnl/single-volunteer_vacancy.php

The background logo on single volunteer pages is missing because apparently it's been deleted from the media library. 
This is now loading the logo from the theme directory instead.

Load svg from theme directory

---

web/app/themes/xrnl/assets/js/xrnl-local-group-tabs.js
web/app/themes/xrnl/assets/sass/local.scss
web/app/themes/xrnl/functions.php
web/app/themes/xrnl/package.json
web/app/themes/xrnl/single-xrnl_local_group.php

The bug is caused by the LG template loading `bootstrap.js`. Bootstrap is already included in the compiled `app.js`, so it shouldn't be necessary to load it again in the first place. But for reasons that I still don't really understand, bootstrap functions like `tab()` and `carousel()` are not available with our regular setup when only `app.js` is loaded.
This now resolves the conflict in `functions.php` by first de-registering `app.js`, then loading `bootstrap.min.js`
and then the `xrnl-local-group-tabs.js` script. It only affects local group pages; all other pages work just like before.
Because:
- owl carousel is no longer in development
- bootstrap already [comes with a carousel](https://getbootstrap.com/docs/4.6/components/carousel/), so we don't need the additional javascript and css

Local group page javascript update

---

web/app/themes/xrnl/assets/sass/local.scss

Moving the controls to the top, as [discussed previously](https://github.com/xrnl/extinction-rebellion-nl/pull/118#issuecomment-766880665).
To my eye it looks a bit less awkward when they are in the top corners, rather than above the images. Comments welcome :)
Mobile, also showing highlight on hover:

Re-position image navigation for local group pages

---

web/app/themes/xrnl/single-xrnl_local_group.php

Hey, I've been meaning to suggest this for a while but there was also a request on MM about it recently.
It would good if the events tab on LG pages showed not only real-life events from the same place, but also
- online events that are organized by the group
- any events organized by multiple groups, where the group is co-organizer
The new filter for the main Events page will use the `Organizer name` field for those cases, which is already being filled in for most events on the website. But we don't have to wait for the filters on the main Events page to be ready before we can use it for the events tab on LG pages.
This PR adjusts the events query to include any events
- matching in physical location (using the `venue_city` field, as before)
- mentioning the group name in the …

Include online events in local group pages

---

web/app/themes/xrnl/archive-meetup_events.php
web/app/themes/xrnl/functions.php

Currently, events are filtered by location where all online events are grouped into one item - Issue with that is that we are mixing events from different local groups while users would want to see events of a local group specifically. This MR solves this by replacing the location-based filter with a filter by organizer.
Downside of this solution is that the 'Organizer' field is not always consistently used (e.g. Extinction Rebellion vs XR) and that they can be quite lengthy - see screenshot below:

Filter events by organizer instead of location

---

web/app/themes/xrnl/acf-json/group_5f1ad30f2103e.json
web/app/themes/xrnl/assets/js/xrnl-local-group-tabs.js
web/app/themes/xrnl/assets/sass/local.scss
web/app/themes/xrnl/single-xrnl_local_group.php

Some minor improvements for the local group pages:
In `xrnl-local-group-tabs.js`
This now checks if there is a hash parameter in the URL that matches one of the tabs, and if so, makes that tab active when the page loads. 
So LGs can use URLs like `extinctionrebellion.nl/groep/amsterdam#actions` to point directly to the Actions tab, for example.
In `group_5f1ad30f2103e.json`
- Add a link to the more detailed [instructions](https://cloud.extinctionrebellion.nl/index.php/s/3eF2cnetwEHRxFk) on NC 
- Update the help text for the events section to reflect the recent change in #125
- In the About us, Demands, and Actions sections, line breaks in the text box will now automatically insert `<p>` tags ([addressing this question](https://organise.earth/xr-netherlands/pl/ms8bxm3mh7gkjbnf3j6exiuxbc) …

Local group page updates

---

web/app/themes/xrnl/archive-meetup_events.php

Small follow-up to #130––
String translation wasn't working without specifying the `theme-xrnl` text domain.

Make event filter labels translatable

---

web/app/themes/xrnl/acf-json/group_5e903166ebd61.json
web/app/themes/xrnl/assets/sass/community.scss
web/app/themes/xrnl/community_group-archive.php
web/app/themes/xrnl/functions.php
web/app/themes/xrnl/package.json
web/app/themes/xrnl/single-community_group.php

This is a bit of a hodgepodge of bugfixes and features for the community group pages. 
1. Added support for `author` and `revision`, so that groups can own their page and track revisions.
2. Added a custom field for twitter.
3. Hero section: currently this doesn't work well because groups use very different photos and graphics. A problem with `background-size: cover` is that some essential parts of images can get cut off on some screen sizes. Another problem is that some groups use text on their cover image, which clashes with the overlaid title.
I've now 
- made the cover image a regular `<img>`, so that it's always shown in full
- removed the overlaid title and increased the size of the main heading underneath
(Some of this is currently done with inline css on some pages 🙀)
4. Added …

Community group update

---

config/application.php

Hi @SamLubbers and @DaanMeijer 
Installing ACF and WPML with private-composer-installer seems to be working fine (#126) 🥳 
This now disables plugin and theme updates in the admin panel, like we discussed yesterday

Disable theme and plugin updates from the WP admin

---

web/app/themes/xrnl/acf-json/group_60a19be777aa5.json
web/app/themes/xrnl/functions.php
web/app/themes/xrnl/template-parts/principles-and-values.php

[For this Trello card](https://trello.com/c/dObMIu0J/293-direct-link-to-principles-and-values-on-website).
This PR includes a template-part for the Principles and Values list, similar to the Demands list.
Like for the Demands list, custom fields show up in the XRNL Settings > Editorial tab.
It also provides a shortcode for the P&V list, so that they can be embedded easily on any page by inserting `[xrnl_principles_and_values]`.

Principles & Values template part and shortcode

---

web/app/themes/xrnl/single-xrnl_local_group.php

Quick bugfix for the local group pages / actions tab, where actions without an image still have an `img` element underneath, and the alt text of that non-existing image gets displayed in an unsightly box in many browsers. 
Actions without an image should simply have no `img` element. 
There was already a check for this but it wasn't working properly; replacing `isset` with `!empty` fixes it.

Check that the image field is not empty in local groups/ actions

---

web/app/themes/xrnl/header.php

I've disabled the cookies from Matomo as described by Fleur in [this task](https://trello.com/c/ldGuw5Gu)
I got this new tracking code by going to the [tracking code page](https://extinctionrebellion.nl/matomo/index.php?module=CoreAdminHome&action=trackingCodeGenerator&idSite=1&period=day&date=yesterday&idContainer=78IMS3NI) of Matomo, click on "advance options", click on "disable tracking cookies" and copy pasting the new tracking code.

disable Matomo cookies

---

web/app/themes/xrnl/assets/sass/form.scss
web/app/themes/xrnl/assets/sass/join.scss
web/app/themes/xrnl/assets/sass/petition.scss
web/app/themes/xrnl/assets/sass/rwb.scss

The main purpose of this change is to:
1. [adding an opt-in](https://trello.com/c/WplmXcny), so people give explicit consent for getting contacted by XR
2. [showing the field labels](https://trello.com/c/SDEqWeJ2), so people know why we ask certain data (such as phone number and municipality.
Of course, when working on this I got frustrated by the inconsistent styles so I also changed them so that there is consistent font-type, font-size, margins and paddings.
Also I removed all redundant code from this `scss` file, and documented and organised the file so that we better understand what the effect is of all that custom css.
Note that if you test this locally you won't see the opt-in option. I need to add that to the Action Network form after we deploy the new css
Here is how the form …

Action Network form improvements

---

web/app/themes/xrnl/functions.php

This disables the `users` endpoint from the REST API in order to prevent Wordpress from exposing usernames. See [this trello task](https://trello.com/c/v8y2OLuM/287-wordpress-exposing-usernames).

Disable users API endpoint

---

web/app/themes/xrnl/functions.php

This creates a new user role for local groups with custom capabilities, as discussed in [this trello card](https://trello.com/c/4S9UUSnu/182-security-users-minimal-permissions).
1. Creates a new role `xrnl_group` & gives it permission to
- edit own posts (but not publish new posts)
- edit own pages (but not publish new pages)
- delete own posts
- upload media files
2. Adds custom capabilities to the `meetup_events` post type
3. Allows xrnl_group, editor, and admin users to
- create, edit & delete own events
- edit & delete others' events

Custom user role for local groups

---

web/app/themes/xrnl/functions.php

Let local groups, editors, and admins edit other users' meetup events.

Add permission to edit others' meetup events

---

web/app/themes/xrnl/acf-json/group_6060f0baa2615.json
web/app/themes/xrnl/acf-json/group_6103d882da0fa.json
web/app/themes/xrnl/functions.php
web/app/themes/xrnl/how_we_work.php
web/app/themes/xrnl/structure_circles.php

@franei people in the integration circle are planning to add a lot of relevant information to the [how we work](https://extinctionrebellion.nl/aan-de-slag-bij-xr/) page so that people can learn all they need to know to help out as a volunteer in XR.
The problem with that page is that it's one big blog of text that is very hard to navigate. Thats' why they would like to add foldout sections just like in the [structure](https://extinctionrebellion.nl/structuur) page. 
What I've done in this PR is:
When using these custom fields I noticed that it was very hard to add information to the fold-out sections
Now it's much easier, with more space for the text and a `visual` option to see the rendered html.
This is how the new page looks like (of course, they will add many more sections):

How we work template & custom fields

---

composer.json
composer.lock
web/app/themes/xrnl/package.json

- Update Wordpress from 5.6 to 5.8
- Update Wordpress plugins
- Remove outdated npm packages

Security updates

---

web/app/themes/xrnl/acf-json/group_5d9678d92c76e.json
web/app/themes/xrnl/front-page.php

@franei the rebellion coordinators wanted to have the banner for the rebellion on the website before they send out the next newsletter on Monday (in less than 12 hours). This week I've had to postpone and postpone, and I've ended up doing this now in a couple of hours. Because they want it so urgently I'll again merge & deploy straight away :roll_eyes: but I would still value your feedback when you have some time :pray:  
I've made 2 main improvements to the home page:
1. the banner for a highlighted event (in this case the rebellion event)
2. improvements to the hero section
Here is how it looks on desktop and on mobile
A few things to note about this banner:
1. you can change the text & link from Wordpress, but not the colours at the moment
2. the whole banner is clickable (I chose this …

Banner home page

---

web/app/themes/xrnl/package.json

This has not been an issue so far because npm throws transitive dependencies in the same node_modules as direct dependencies.
All these dependencies were also dependencies of `laravel-mix` so they were present, but we depend on them directly so they should be added.

Add missing dependencies for generating the theme
